# Generated by Django 4.1.1 on 2023-06-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_numer',
            new_name='student_number',
        ),
    ]
